name: Continous Integration
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        id: cache-stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-store-${{ hashFiles('generator/generator.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack-store-

      - name: Install stack
        run: curl -sSL https://get.haskellstack.org/ | sh
        if: matrix.os == 'macos-10.15'

      - name: Build generator
        run: cd generator && stack build

      - name: Package generator
        run: |
          mkdir package
          cd generator
          cp $(stack path --dist-dir)/build/generator/generator ../package/myRetroGenerator
          cd ..
          cp -r static template Makefile package/

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: generator-${{ runner.os }}
          path: package
